Added --filename option to simulator result output
DeviaVir/zenbot pull request #194
Opened 2017-05-26 20:38 UTC by tomahock

2017-05-27 10:12 UTC, DeviaVir requested changes

2017-05-27 10:12 UTC, DeviaVir commented on commands/sim.js
> +          }
why not just `var out_target = so.filename || 'sim_result.html'`?

2017-05-29 15:19 UTC, tomahock commented
Done :)

2017-05-30 05:51 UTC, DeviaVir approved these changes
:+1:

2017-06-03 04:19 UTC, merged