Zenbot Bitstamp extension
DeviaVir/zenbot pull request #266
Opened 2017-06-11 19:57 UTC by eigilb

The increase in traffic on the exhanges we have seen lately can be quite a challenge when developing a trading bot. Traffic conguestion, DOS attacks, broken connections and what not. On the exchange side they need tu have mechanisms to conrol the traffic. One measurement the bot are facing is the risk of being blocked with rate limiting. With the use of HTTP requests a lot of connecting, closing and reconnecting are taking place, and it is easy to get into a rate limit situation.

In the interface layer for Bitstamp we have used websockets for getting data. Unfortunately Bitstamp only have implemented two public channel, tickets and orderbook. Luckily it is tickers and orderbook that generate most of the traffic from the exchange. In short it means that we have to use traditional HTTP requests for the private authenticated functions. But use of websockets functions means we can connect once per session and listen for streaming data without the fear of being locked out by a rate limit block.

The Bitstamp interface may still have some bugs and shortcomings, but hopefully such problems can be sorted out.

2017-06-12 09:40 UTC, DeviaVir requested changes
the `update-products.sh` seems to be missing, could you still add this?

Really like the websocket path you took, and it looks great. Just a few nits.

2017-06-12 09:40 UTC, DeviaVir commented on extensions/exchanges/bitstamp/exchange.js
> +// it ha ben neccessary to get it from
`it ha ben`?

2017-06-12 09:40 UTC, DeviaVir commented on extensions/exchanges/bitstamp/exchange.js
> +	balance.currency = body[opts.currency.toLowerCase() + '_available']
indentation problems start here

2017-06-12 09:40 UTC, DeviaVir commented on extensions/exchanges/bitstamp/exchange.js
> +	}
indentation

2017-06-12 14:27 UTC, DeviaVir commented
@eigilb could you still add an `update-products.sh`?

2017-06-12 14:54 UTC, eigilb commented
I have not found a function for that on Bitstamp. The products file is done manually, but thanks for asking ;-)

2017-06-12 14:59 UTC, DeviaVir submitted a review, later dismissed

2017-06-12 15:00 UTC, DeviaVir commented
@eigilb I see, that's a bit sad, but alright then. Rest looks good to me, I'll leave the PR open for a day and if no one else speaks up let's merge this.

2017-06-12 21:48 UTC, eigilb commented
@DeviaVir, will You put this on hold for a while? During testing I have found an issue that needs some work.

2017-06-14 09:23 UTC, DeviaVir commented
@eigilb you might find the changes I made here interesting: https://github.com/carlos8f/zenbot/compare/master...DeviaVir:eigilb-master?expand=1

2017-06-14 14:30 UTC, eigilb commented
@DeviaVir, as a new user of Bitstamp, I think you may find this infornation interesting or at least useful.

The Bitstamp API has a straight forward market order API function, but the limit order has a somewhat peculiar option. This option is called "limit_price" and it is required if we don't use another option. "daily_order" (which is optional).

The 'limit_price' simply means that another order in added in the opposite direction.. It is activated when original order is executed and and the 'limit_price' then gets executed if the the market price reaches the set 'limit price'.

The call won't sell unless we have a value in "limit_price" (tested).   It is described like this in the Bitstamp docs: 

"If the order gets executed, a new sell order will be placed, with 'limit_price' as its price.", meaning it will place a buy order for the price of "limit_price". That price need to be lower than the sell price and with a corresponding amount.  

An example: You set a sell price of 1200. At the same time you set a buy 'limit_price' of 1100. The buy order is activated as soon as the sell order is executed. If the market price goes down to 1100, the 'limit_price' order is executed to buy back the asset.

To use a limit call, I guess some logic to cancel the "limit_price" order is needed.
  

There is also another option. Instead we can use the "daily_order" option, which means that the same order is automatically canceled at midnight if not executed or canceled before that. Using this option means we need to have two new prototypes where the value of "daily_order" is set to "true"  because the existing bitstamp node library is missing this option.
```
  Bitstamp.prototype.buyDaily = function(market, amount, price, callback) {
    this._post(market, 'buy', callback, {
      amount: amount,
      price: price,
      daily_order: true
    });
  }
```
And the same for "sellDaily()"

2017-06-21 18:37 UTC, tuxitor commented
@DeviaVir 
I think kost of the issues are resolved now

2017-06-21 18:45 UTC, DeviaVir commented on commands/buy.js
> +	}
indenting issue

2017-06-21 18:45 UTC, DeviaVir commented on commands/sell.js
> +	}
indenting issue

2017-06-21 18:45 UTC, DeviaVir commented on conf-sample.js
> +// to enable Bitfinex trading, enter your API credentials:
`Bitfinex` => `Bitstamp`

2017-06-21 18:45 UTC, DeviaVir commented on extensions/exchanges/bitstamp/exchange.js
> +args.forEach(function(value) {
maybe this should live in a function that is called before it is needed instead of always executed?

2017-06-21 18:45 UTC, DeviaVir commented on extensions/exchanges/bitstamp/exchange.js
> +		if (wstrades.length > 30) wstrades.splice(0,10)
weird indenting

2017-06-21 18:45 UTC, DeviaVir commented on extensions/exchanges/bitstamp/exchange.js
> +      console.error(('\nBitstamp API is not answering! unable to call ' + method + ',OB retrying in ' + to + 's').red)
`OB retrying`, what is OB?

2017-06-21 18:45 UTC, DeviaVir commented on extensions/exchanges/bitstamp/exchange.js
> +    historyScan: false,
just verifying, no history for bitstamp available?

2017-06-21 18:45 UTC, DeviaVir commented on package.json
> +		"autobahn": "^17.5.2",
weird indenting

2017-06-21 18:45 UTC, DeviaVir commented on extensions/exchanges/bitstamp/exchange.js
> +      } else {
perhaps we can be more explicit here and just say
`if (opts.order_type === 'taker') {`

2017-06-21 19:50 UTC, tuxitor commented on extensions/exchanges/bitstamp/exchange.js
> +      } else {
Added a comment here to improve clarity

2017-06-21 19:50 UTC, tuxitor commented on extensions/exchanges/bitstamp/exchange.js
> +    historyScan: false,
Confirmed. No history

2017-06-21 19:50 UTC, tuxitor commented on extensions/exchanges/bitstamp/exchange.js
> +      console.error(('\nBitstamp API is not answering! unable to call ' + method + ',OB retrying in ' + to + 's').red)
Stupid typo

2017-06-21 19:52 UTC, tuxitor commented on commands/buy.js
> +	}
Hm.. Have tabstops set to 2 without filling with spaces. Expands in other environments

2017-06-21 19:56 UTC, tuxitor commented on extensions/exchanges/bitstamp/exchange.js
> +args.forEach(function(value) {
I dont quite understand the meaning of this. The internal logic is still a bit "secret". At least I have added comments where this implementation differs from the others. Any suggestions are welcome from a node programmer. This is project is my first attempt to live in the "callback hell".

2017-06-30 17:56 UTC, tuxitor commented
@carlos8f @DeviaVir 
Please tak a look at this. It is probably very interesting for a lot of the community:
https://github.com/tuxitor/zenbot/blob/master/docs/Zentalk.md

2017-07-03 08:55 UTC, DeviaVir commented
@tuxitor Definitely looks interesting, but it has become quite a mess. I spot a few typo's and wrong indents, but a bit too many to call them all out individually.

It would also be a lot easier if the zentalk and bitstamp code would be separated in different PR's (different branches). Is this something you can still do? Otherwise I'll try to update your code from my end.

2017-07-03 10:42 UTC, tuxitor commented
I am far away from home this week, but may have some free spots and be able to do some fix up. Ideally the Zentalk addition should have been done in cooperation with @carlos to find the best approach. In the longer term I think headless networking model is the right direction to go. In general I think it may be possible make an addition like this conditionally included

2017-07-03 10:45 UTC, tuxitor commented
I have to add that some help from an experienced node programmer would be much appreciated

2017-07-05 15:38 UTC, closed without merging