Backfill bitfinex with v2 && refactoring err.match function
DeviaVir/zenbot pull request #276
Opened 2017-06-12 11:42 UTC by nao0811ta

2017-06-12 13:29 UTC, DeviaVir requested changes

2017-06-12 13:29 UTC, DeviaVir commented on commands/backfill.js
> +              if (exchange_id === 'bitfinex' && !marker.from){
We will really need to find a different solution for this, logic for exchanges should be limited to exchanges, and never live outside of that.

2017-06-12 13:29 UTC, DeviaVir commented on commands/backfill.js
> +            if (exchange_id === 'bitfinex'){
Same comment as before: this logic should happen in the exchange.js

2017-06-12 13:29 UTC, DeviaVir commented on extensions/exchanges/bitfinex/exchange.js
> +    return 't' + product_id.split('-')[0] + '' + product_id.split('-')[1]
why not just `return 't' + joinProduct(product_id)`?

2017-06-12 13:29 UTC, DeviaVir commented on extensions/exchanges/bitfinex/exchange.js
> +        args.end = opts.to
in the commands you are setting this to `new Date().getTime()`, why not just do that here?

2017-06-12 13:30 UTC, DeviaVir commented
I also think there must be a nicer way than to use `function2` for the v2 things, maybe they should just live in different class?

2017-06-12 14:50 UTC, nao0811ta commented on commands/backfill.js
> +              if (exchange_id === 'bitfinex' && !marker.from){
Thank you
if opts.to is null , bitfinex response 1 years ago data.
hm.. I'm thinking..

2017-06-12 14:51 UTC, nao0811ta commented on commands/backfill.js
> +            if (exchange_id === 'bitfinex'){
got it..

2017-06-12 14:52 UTC, nao0811ta commented on extensions/exchanges/bitfinex/exchange.js
> +    return 't' + product_id.split('-')[0] + '' + product_id.split('-')[1]
I thought that. I forget to fix.

2017-06-12 14:58 UTC, nao0811ta commented
@DeviaVir 
I'm sorry. and thank you, it must create new v2 class. but I don't have many time to survey v2 new API. so I only implemented backfill function for me ASAP. So, I hope that helps someone. 
@nedievas

2017-06-13 02:41 UTC, nao0811ta commented
@nedievas  is working for v2
and my implementation is bad 
so close PR.

2017-06-13 02:41 UTC, closed without merging